language: generic
if: tag IS present

before_install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.462.sh
  - chmod +x linux-install-1.10.1.462.sh
  - sudo bash linux-install-1.10.1.462.sh
  - npm install -g shadow-cljs

script:
  - npm run build

deploy:
  provider: npm
  email: $EMAIL
  api_key: $AUTH_TOKEN
